Nama: Wilson

NPM: 6182001039

# Matriks di Python

Pada modul ini, kita akan mencari solusi untuk SPL dengan eliminasi Gauss dan backward substitution. Sebelum mengimplementasikan kedua metode tersebut, kita terlebih dahulu mempelajari representasi matriks pada Python dan beberapa hal berkaitan dengan matriks yang mungkin akan dibutuhkan di modul ini (tentu tidak semua kita bahas, silakan eksplorasi mandiri untuk lebih memperkaya pengetahuan kalian mengenai sintaks di Python). Untuk representasi matriks, kita akan menggunakan fungsi array yang ada pada library numpy.
Source untuk belajar NumPy Array: https://www.w3schools.com/python/numpy/numpy_creating_arrays.asp

In [1]:
import numpy as np
from numpy.linalg import matrix_rank #untuk menghitung rank

Kita akan mencoba untuk membuat matriks 
$$A=\left[\begin{matrix}
1 & 2 & 3\\
2 & 3 & 4
\end{matrix}\right]$$

Untuk membuat matriks, gunakan perintah `np.array([[a11,a12,..,a1n],...,[am1,am2,...,amn]])` seperti pada contoh berikut ini:

In [2]:
A = np.array([[1,2,3],[2,3,4]])
print(A)

[[1 2 3]
 [2 3 4]]


**TUGAS 1:** Buatlah matriks $B$ berikut ini:
$$B=\left[\begin{matrix}
1 & 2 & 3
\end{matrix}\right]$$

In [3]:
# Tuliskan kode Anda untuk menjawab TUGAS 1A = np.array([[1,2,3],[2,3,4]])
B = np.array([1,2,3])
print(B)

[1 2 3]


Terkadang kita butuh membuat matriks yang masih kosong. Untuk mendefinisikan matriks yang belum berisi, kita dapat menyiasati dengan membuat membuat matriks berukuran $m\times n$ yang berisi 0. Untuk membuat matriks yang berisi 0, dapat digunakan perintah `np.zeros((m,n), dtype=(tipe data))`. Misalkan kita ingin membuat matriks $C_{2\times2}$ yang belum berisi dengan tipe data bilangan bulat.

In [4]:
C = np.zeros((2,2), dtype=int)
print(C)

[[0 0]
 [0 0]]


Untuk mengisi array, kita juga dapat meminta masukkan dari pengguna. Untuk meminta masukkan dari pengguna, kita dapat menggunakan perintah `input()`

In [6]:
for i in range(2):
    for j in range(2):
        C[i,j]= int(input())
print(C)

[[1 1]
 [1 1]]


**TUGAS 2:** Apakah fungsi `int()` yang digunakan sebelum `input()`?

**JAWAB 2:**
Agar tipe data yang dimasukkan berupa integer

**TUGAS 3:** Buatlah matriks berkuran $3\times 3$ dengan nama $D$. Kemudian mintalah input untuk mengisi seluruh elemen pada matriks $D$

In [10]:
# Tuliskan kode program untuk menjawab TUGAS 3
D = np.zeros((3,3), dtype=int)
for i in range(3):
    for j in range(3):
        D[i,j]= int(input())
print(D)

[[1 2 3]
 [4 5 6]
 [1 1 1]]


Salah satu kelebihan python adalah kita dapat melakukan slicing terhadap isi array dengan cukup mudah. Apa yang dimaksud dengan slicing? Slicing adalah mengambil elemen array dari suatu indeks hingga sebelum indeks akhir.

Untuk menentukan indeks array yang mau diambil, digunakan sintaks: `[start:end]`

Kita juga dapat menentukan step dari indeks yang mau diambil dengan sintaks: `[start:end:step]`

Jika `start` tidak ditentukan, maka nilai default-nya adalah 0.

Jika `end` tidak ditentukan, maka nilai default-nya adalah panjang array di dimensi tersebut.

Jika `step` tidak ditentukan, maka nilai default-nya adalah 1.

Sebagai contoh, misalkan kita ingin mengambil isi array $A$ pada baris 1 di kolom 1 dan 2 saja.


In [12]:
print(A[0, 0:2])

[1 2]


Perhatikan:

* indeks array mulai dari 0
* perintah `0:2` artinya mengambil di indeks 0 dan 1 (sebelum 2)

**TUGAS 4:** Ambilah elemen array D di baris 2 dan kolom 2 dan 3

In [13]:
# Tuliskan kode program Anda untuk menjawab TUGAS 4
print(D[1, 1:4])

[5 6]


Silakan pelajari lebih jauh mengenai array slicing dari: https://www.w3schools.com/python/numpy/numpy_array_slicing.asp/

Pastikan Anda sudah benar-benar paham mengenai slicing array sebelum lanjut ke materi berikutnya di modul ini agar Anda bisa mengerjakan tugas yang diberikan dengan lebih lancar.

Anda dapat melakukan operasi-operasi matematika pada array yang berukuran sama. Misalkan kita ingin menjumlahkan matriks $B$ dengan matriks $A$ pada baris 2.

In [17]:
print(B+A[1,])

[3 5 7]


Kita juga dapat melakukan perkalian per elemen untuk dua matriks yang berukuran sama. Perhatikan perkalian ini bukan perkalian matriks, karena perkalian matriks tidaklah mengalikan per elemen matriks. Cobalah cari tahu bagaimana cara melakukan perkalian matriks. Pada modul ini, yang akan diberitahu adalah perkalian per elemen matriks.

In [18]:
print(B*A[1,])

[ 2  6 12]


**TUGAS 5:** Cobalah untuk menjumlahkan baris pertama pada matriks $A$ dengan baris kedua dari matriks $A$. Untuk mengerjakan tugas ini, jangan gunakan perulangan, tetapi gunakan slicing pada matriks.

In [19]:
#Tuliskan kode program Anda untuk menjawab TUGAS 5
print(A[0,] + A[1,])

[3 5 7]


**TUGAS 6:** Jumlahkan baris kedua matriks $A$ dengan baris pertamanya yang sudah dikali dengan 3. Untuk mengerjakan tugas ini, jangan gunakan perulangan, tetapi gunakan slicing pada matriks.

In [20]:
#Tuliskan kode program Anda untuk menjawab TUGAS 6
print(A[1,] + (A[0,]*3))

[ 5  9 13]


Seringkali kita butuh membuat duplikat untuk variabel yang sudah ada (misal: untuk melakukan pertukaran isi variabel. kita biasa menggunakan variabel temp sebagai variabel penampung). Untuk menduplikat isi matriks, kita tidak dapat langsung menggunakan variabel assignmetn `=`. Jika kita menduplikat isi matriks menggunakan operator `=`, maka kita tidak menduplikat isinya tetapi membuat variabel penampung menunjuk ke "alamat" yang sama dengan matriks yang ingin diduplikat. Sehingga perubahan terhadap yang 1 mengakibatkan perubahan terhadap variabel lainnya.

Oleh karena itu, kita perlu menggunakan perintah `(array).copy()` untuk menduplikat isi matriks. Sebagai contoh, misalkan kita ingin menduplikat seluruh isi matriks $A$ ke matriks $E$.

In [21]:
E = A.copy()
print(E)

[[1 2 3]
 [2 3 4]]


Source untuk belajar Array Copy:https://www.w3schools.com/python/numpy/numpy_copy_vs_view.asp 

# Mencari Solusi SPL dengan Eliminasi Gauss

Salah satu cara untuk menemukan solusi dari SPL adalah dengan melakukan eliminasi Gauss dan backward substitution. Pada eliminasi Gauss, elemen-elemen matriks dieliminasi hingga matriks menjadi matriks segitiga atas. 

**TUGAS 7:** Buatlah fungsi dengan nama EG untuk mengubah matriks $A$ dan vektor $b$ hingga matriks $A$ menjadi matriks segitiga atas.

In [36]:
import numpy as np
def EG(A, b):
    """
    A: matriks koefisien berukuran mxm
    b: vektor konstanta
    
    return:
    A: matriks A yang sudah menjadi segitiga atas
    b: vektor konstanta yang berubah sesuai dengan operasi yang dilakukan terhadap matriks A
    Jika A tidak dapat dibuat menjadi segitiga atas, kembalikan A dan b yang berupa matriks 0.
    Hal ini untuk penanda bahwa tidak dapat ditemukan solusi.
    """
    # N = A.shape[0]

    # for i in range(1, N):
    #     for j in range (i+1, N):
    #         temp = A[j, i]/A[i, i]
    #         A[j, :] = A[j, :] - temp*A[i, :]
    #         b[j] = b[j] - temp*b[i]
    
    # return A, b

    A_copy = A.copy()
    b_copy = b.copy()
    n = A.shape[0]
    if(A_copy[0,0] == 0):
        for i in range(n):
            if A_copy[i,0] != 0:
                A_temp = A_copy[i, 0:n]
                b_temp = b_copy[i, 1]
                A_copy[i, 0:n] = A_copy[0, 0:n]
                A_copy[0, 0:n] = A_temp
                b_copy[i, 0] = b_copy[0, 1]
                b_copy[0, 0] = b_temp
                break
        if A_copy[0, 0] == 0:
            A_copy = np.zeros((n, n), dtype=float)
            b_copy = np.zeros((n, 1), dtype=float)
            return A_copy, b_copy
        for i in range (n):
            for j in range (i+1, n):
                pv = A_copy[j][i] / A_copy[i][i]
                A_copy[j, 0:n] -= pv * A_copy[i, 0:n]
                b_copy[j, 0] -= pv * b_copy[i, 0]
        return A_copy, b_copy



    



**TUGAS 8:** Setelah membuat fungsi untuk melakukan eliminasi Gauss, buatlah fungsi untuk melakukan backward substitution. Masukan untuk fungsi ini adalah matriks $A$ yang sudah merupakan matriks segitiga atas dan vektor $b$.

In [37]:
def BackSub(A,b):
    """
    A: matriks segitiga atas
    b: vektor konstanta
    
    return:
    x: sebuah vektor yang merupakan solusi dari SPL
    """
    A, b = EG(A, b)
    N = A.shape[0]
    x = np.zeros(N, float)
    x[N] = b[N] / A[N, N]
    for i in range(N, 0, 0):
        x[i] = b[i]
        for j in range(i + 1, N-1):
            x[i] = x[i] - A[i][j] * x[j]
        x[i] = x[i]/A[i][i]
    
    return x


**TUGAS 9:** Ujilah fungsi EG dan fungsi BackSub yang sudah Anda buat dengan matriks A dan b yang berasal dari masukan pengguna. Lengkapi bagian kode di bawah ini untuk memanggil fungsi EG, memeriksa apakah ada solusi atau tidak, memanggil fungsi BackSub jika ada solusi, dan menampilkan solusinya/tidak ada solusi.

In [38]:
N = int(input())
A = np.zeros((N,N), dtype=float)
b = np.zeros((N,1), dtype=float)
for i in range(N):
    for j in range(N):
        A[i,j] = float(input())
    b[i]=float(input())
#Membuat augmented matrix untuk memeriksa rank
A_b = np.concatenate((A,b), axis=1)
rank_Ab = matrix_rank(A_b)

if rank_Ab == N:
    A_copy, b_copy = EG(A, b)
    x = BackSub(A_copy. b_copy)
    for i in range(N):
        print('X%d = %0.2f' %(i,x[i,0]), end = '\n')

#Hitunglah rank untuk matriks A, kemudian tentukan apakah SPL ini memiliki solusi tunggal. 
#Jika ya, lanjut ke perintah berikutnya, jika tidak maka tidak perlu memanggil fungsi EG dan BackSub kemudian tampilkan jenis solusi dari SPL ini.
#Lengkapi kode program ini dengan memanggil fungsi EG dan BackSub, kemudian tampilkan solusinya.

TypeError: cannot unpack non-iterable NoneType object

**TUGAS 10:** Buatlah fungsi untuk eliminasi Gauss dengan partial pivoting.

In [ ]:
def PEG(A,b):
    """
    A: matriks koefisien berukuran mxm
    b: vektor konstanta
    
    return:
    A: matriks A yang sudah menjadi segitiga atas
    b: vektor konstanta yang berubah sesuai dengan operasi yang dilakukan terhadap matriks A
    Jika A tidak dapat dibuat menjadi segitiga atas, kembalikan A dan b yang berupa matriks 0.
    Hal ini untuk penanda bahwa tidak dapat ditemukan solusi.
    """
A_copy = A.copy()
b_copy = b.copy()
n = A.shape[0]
for i in range(N):
    for j in range(i+1, N):
        pv = A_copy[j][i] / A_copy[i][i]
        A_copy[j, 0:n] -= pv * A_copy[i, 0:n]
        b_copy[j, 0] -= pv*b_copy[i, 0]

**TUGAS 11:** Ujilah fungsi PEG dan fungsi BackSub yang sudah Anda buat dengan matriks A dan b yang berasal dari masukan pengguna. Lengkapi bagian kode di bawah ini untuk memanggil fungsi PEG, memeriksa apakah ada solusi atau tidak, memanggil fungsi BackSub jika ada solusi, dan menampilkan solusinya/tidak ada solusi.

In [ ]:
N = int(input())
A = np.zeros((N,N), dtype=float)
b = np.zeros((N,1), dtype=float)
for i in range(N):
    for j in range(N):
        A[i,j] = float(input())
    b[i]=float(input())

#Lengkapi kode program ini dengan memanggin fungsi PEG dan BackSub. 
#Sebelum Anda memanggil fungsi BackSub, pastikan SPL Anda memiliki solusi (dengan menghitung rank seperti pada contoh uji coba EG)!

# Metode Iterasi Jacobi

Untuk melakukan iterasi Jacobi, kita perlu mengubah SPL $Ax=b$ menjadi $x=Bx+C$. Untuk mendapatkan matriks $B$ dan $c$, pertama kita akan memisahkan diagonal $D$ dari matriks $A$ sehingga:
$$A=D+(A-D)$$
dan kita dapat menuliskan:
$$x=D^{-1}(D-A)x+D^{-1}b$$

Matriks $B = D^{-1}(A-D)$ dan $c=D^{-1}b$. Kita akan mencoba untuk menentukan matriks $B$ dan $c$ dari matriks $A$ dan $b$ berikut ini. perintah `np.diagflat([15]*n)` akan membuat matriks diagonal berukuran $n\times n$ dengan diagonalnya adalah 15. Source untuk perintah `numpy.diagflat`: https://numpy.org/doc/stable/reference/generated/numpy.diagflat.html. Perintah ini dilakukan agar matriks A memiliki diagonal yang dominan.

In [28]:
#Mendefinisikan matriks A dan b dengan bilangan random
rndm = np.random.RandomState(1234)

n=10
A = rndm.uniform(size=(n, n)) + np.diagflat([15]*n)
b = rndm.uniform(size=n)

Sekarang kita akan mencoba mengkonstruksi matriks $D, B, c$. Untuk mengambil diagonal dari matriks $A$, Anda dapat menggunakan perintah `np.diag`. Fungsi tersebut akan mengembalikan sebuah matriks 1D jika parameternya adalah matriks 2D dan sebaliknya. Sebagai contoh, cobalah sintaks berikut ini: 

In [27]:
Contoh2D = np.array([[1,2], [3,4]])
print(Contoh2D)
Contoh1D = np.diag(Contoh2D)
print(Contoh1D)

# Membuat matriks 2D dengan diagonalnya adalah Contoh1D
Diag2D = np.diag(Contoh1D)
print(Diag2D)

[[1 2]
 [3 4]]
[1 4]
[[1 0]
 [0 4]]


**TUGAS 12:** Dari contoh tersebut, perhatikan penggunakan fungsi `numpy.diag` dan pahami fungsinya. Dengan memanfaatkan fungsi tersebut, buatlah matriks $D$ kemudian buatlah matriks $B$ dan matriks $c$. (Dalam membuat tugas 3, Anda tidak boleh mengubah isi matriks $A$ dan $b$)

In [ ]:
# Tuliskan kode Anda di sini untuk menjawab Tugas 12
D_diag = np.diag(B)

**TUGAS 13:** Sebelum melakukan iterasi Jacobi untuk mencari solusi dari SPL $Ax=b$, periksa terlebih dahulu norm dari matriks $B$ (periksa apakah $\|B\|\leqslant 1$). Gunakan fungsi `linalg.norm` dari library `numpy` untuk mencari norm dari matriks $B$. Source untuk menggunakan fungsi `linalg.norm`: https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html

In [ ]:
# Tuliskan kode Anda di sini untuk menjawab Tugas 13
from numpy import linalg as LA
LA.norm(b)


**TUGAS 14:** Buatlah sebuah fungsi untuk melakukan iterasi Jacobi. Di dalam fungsi tersebut, buatlah matriks $D, B,$ dan $c$ seperti yang sudah Anda lakukan sebelumnya.

In [ ]:
def IterJacobi (A, b, eps = 1e-4, n_iter = 50):
    """
    Parameter:
    A : Matriks koefisien
    b : Vektor konstanta pada SPL
    eps : batas toleransi error
    n_iter: maksimum iterasi yang diperbolehkan
    
    Return value:
    x : solusi dari SPL
    """
    N = A.shape[0]
    if eps is None:
        eps = np.zeros(N)

    D = np.diag(A)
    R = A - np.diagflat(D)
                                                                                                                                                                     
    for i in range(n_iter):
        x = (b - np.dot(R,x)) / D
    return x

In [ ]:
# Periksa hasil Anda solusi Anda:
x = IterJacobi(A,b)
print(x)
print(A @ x - b)

**TUGAS 15:** Cobalah untuk matriks $A$ dan $b$ yang lain. Mintalah input untuk matriks $A$ dan $b$. Coba juga untuk matriks $A$ yang nilai pada diagonalnya kecil. Apakah iterasi Jacobi konvergen? Periksa juga nilai dari norm matriks $B$.

In [ ]:
# Tuliskan kode Anda untuk menjawab TUGAS 15
N = int(input())
A = np.zeros((N,N), dtype=float)
b = np.zeros((N,1), dtype=float)
for i in range(N):
    for j in range(N):
        A[i,j] = float(input())
    b[i]=float(input())

A, b = IterJacobi (A, b, eps = 1e-4, n_iter = 50)
for i in range(N):
        print('X%d = %0.2f' %(i,x[i,0]), end = '\n')

# Iterasi Seidel

**TUGAS 16:** Implementasikan iterasi Seidel pada fungsi berikut ini.

In [ ]:
def Seidel (A, b, eps = 1e-4, n_iter = 50):
    """
    Parameter:
    A : Matriks koefisien
    b : Vektor konstanta pada SPL
    eps : batas toleransi error
    n_iter: maksimum iterasi yang diperbolehkan
    
    Return value:
    x : solusi dari SPL
    """
    A_diag = np.diag(np.abs(A)) 


**TUGAS 17:** Cobalah fungsi Seidel  tersebut untuk beberapa matriks $A$ dan $b$. Mintalah input untuk matriks $A$ dan $b$. Perhatikan kekonvergenan dari iterasi Seidel.

In [ ]:
# Tuliskan kode Anda di sini untuk menjawab TUGAS 17
N = int(input())
A = np.zeros((N,N), dtype=float)
b = np.zeros((N,1), dtype=float)
for i in range(N):
    for j in range(N):
        A[i,j] = float(input())
    b[i]=float(input())

A, b = Seidel (A, b, eps = 1e-4, n_iter = 50)
for i in range(N):
        print('X%d = %0.2f' %(i,x[i,0]), end = '\n')